### ISSUE TITLE
请问可以开启pcie4.0吗

### ISSUE THREAD

**Issue by Gydio** [Umenezumi/Hackintosh-GIGABYTE-Z690I-AORUS-ULTRA-LITE#2]
这个主板的缺陷是开启pcie4在windows会报错。请问在mac下面会有啥报错吗？

另外可否分享一下bios配置？

**Comment by Umenezumi** [comment]
你好，我的显卡不支持 PCI-E 4.0 并且我使用的延长线是 3.0, 所以无法回答相关问题，不过根据我看到的评价来看，很多人是可以正常使用 4.0的

bios 配置我有在 Readme 里列出
