### ISSUE TITLE
网卡驱动

### ISSUE THREAD

**Issue by MaxLFG** [Umenezumi/Hackintosh-GIGABYTE-Z690I-AORUS-ULTRA-LITE#4]
感谢分享～
我使用和你相同的主板，使用你分享的0.9.5和0.9.6无法驱动原装的无线网卡，蓝牙连接正常。
有线网卡驱动出现BUG，DHCP获取不到正常的ip地址，更换AppleICL为I210驱动可解决。

目前只有无线网卡无法驱动，无论是Airportitlwm.kext还是itlwm.kext都无法正常驱动wifi，但是bash下kextstat可以显示已经注入驱动。

请问你使用的是Z690I-AORUS-ULTRA-LITE自带的无线网卡Killer Wi-Fi6 AX1650i 160MHz (201NGW)吗？能否交流一下故障如何处理，谢谢！

**Comment by Umenezumi** [comment]
看下 Readme， 我记得我换成了 ax211 应该是。

**Comment by MaxLFG** [comment]
试了很多，发现VT-d off即可解决，谢谢🙏

**Comment by Umenezumi** [comment]
> 试了很多，发现VT-d off即可解决，谢谢🙏

恭喜
